includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/Conv64F.yaml

optimizer:
  name: Adam
  kwargs:
    lr: 0.0001
  other: 
    model: 1e-4
    emb_func: 1e-3
    # NEGMEAN: 0.0001

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True

classifier:
  name: CDKT
  kwargs:
    n_way: 5
    n_support: 5
    kernel: 'bncossim'
    loss: 'ELBO'
    mean: 0.0
    steps: 2
    tau: 0.5 # temparature 0.2 for CUB and 0.5 for MINIimagenet